name: Test all dockerfiles

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-ubuntu:
   runs-on: self-hosted
   steps:
     - uses: shaw1025/test/.github/workflows/build_and_test.yml@main
     - name: Build container image
       run: docker build -t fhe-ubuntu -f docker/ubuntu-jammy.Dockerfile .
     - name: Run tests inside the container
       run: docker run fhe-ubuntu 'bazel test ...:all'
  docker-debian:
   runs-on: self-hosted
   steps:
     - uses: shaw1025/test@main
     - name: Build container image
       run: docker build -t fhe-debian -f docker/debian-bullseye.Dockerfile .
     - name: Run tests inside the container
       run: docker run fhe-debian 'bazel test ...:all'
