name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: shaw1025/test/checkout@main
    - name: Build the Docker image
      run: docker build -t fhe-ubuntu -f docker/ubuntu-jammy.Dockerfile .
