name: Docker Image CI
usethis::use_github_action_check_standard()

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: 'shaw1025/test@main'
      - name: Build the Docker image
        run: echo "test ............"
#      run: docker build -t fhe-ubuntu -f docker/ubuntu-jammy.Dockerfile .
